cloud:
  aws:
    credentials:
      access-key: AKIA4IAJDE2FCNVJR4I2
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false
      
application:
  bucket:
    name: pastebin44
      
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
