aws:
  region: eu-north-1
      
application:
  bucket:
    name: pastebin44

interval: PT1M # ISO format
      
spring:
  thymeleaf:
    cache: false
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always